"""initial schema

Revision ID: 6509b93e71a8
Revises: 
Create Date: 2026-06-26 05:14:38.818910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6509b93e71a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=32), nullable=False),
    sa.Column('client_type', sa.Enum('PERSON', 'COMPANY', name='clienttype'), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('fiscal_code', sa.String(length=32), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('practice_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('folder_relative_path', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_relative_path')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.create_index(op.f('ix_clients_fiscal_code'), 'clients', ['fiscal_code'], unique=False)
    op.create_index(op.f('ix_clients_practice_number'), 'clients', ['practice_number'], unique=False)
    op.create_index(op.f('ix_clients_vat_number'), 'clients', ['vat_number'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('CLIENT', 'DOCUMENT', name='entitytype'), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'CHOICE', name='customfieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'field_key', name='uq_custom_field_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_entity_type'), 'custom_field_definitions', ['entity_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('CLIENT', 'DOCUMENT', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=1024), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'entity_id', name='uq_custom_field_value_entity')
    )
    op.create_index(op.f('ix_custom_field_values_entity_id'), 'custom_field_values', ['entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_entity_type'), 'custom_field_values', ['entity_type'], unique=False)
    op.create_index(op.f('ix_custom_field_values_field_definition_id'), 'custom_field_values', ['field_definition_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_folders_client_id'), 'folders', ['client_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('TO_VERIFY', 'CATALOGUED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_extension'), 'documents', ['extension'], unique=False)
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'RENAMED', 'MOVED', 'MODIFIED', 'CATALOGUED', name='historyeventtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_history_document_id'), 'document_history', ['document_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_document_history_document_id'), table_name='document_history')
    op.drop_table('document_history')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_extension'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_client_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_custom_field_values_field_definition_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_type'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_custom_field_definitions_entity_type'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_clients_vat_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_practice_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_fiscal_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
